GET http://store-alisa.herokuapp.com/products
Accept: application/json

###
POST http://store-alisa.herokuapp.com/products
Content-Type: application/x-www-form-urlencoded

name=butterfly&price=11

###
